---
- hosts: localhost
  become: no

  tasks:
    - name: Enable memory leak in the business backend
    command: kubectl exec --namespace=easytravel -it $(kubectl get pod -l "type=backend-pod" --namespace=easytravel -o jsonpath='{.items[0].metadata.name}') -- curl "http://localhost:8080/services/ConfigurationService/setPluginEnabled?name=MediumMemoryLeak&enabled=true"
    ignore_errors: yes
    delegate_to: easyTravel
